tasks:
  - init: |
      sudo apt-get install -y python3-opencv
      pip install --upgrade poetry
      poetry install
    command: |
      echo "Hello world"

vscode:
  extensions:
    - ms-python.python
